### ISSUE TITLE
[Auto Generated]Plugin error occurred: org.graalvm.polyglot.PolyglotException: SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by mmfazrin-phcc-gov** [yzhengfei/ai-coding#125]
:warning:_`[Auto Generated Report]-=C0DA96F347260C99B2C57117692C8AA6=-`_

## Description

org.graalvm.polyglot.PolyglotException: SyntaxError: Unexpected end of input

## Environments
> **Plugin version: 2024.1.15**

JetBrains Rider 2024.2.5
Build #RD-242.22855.90, built on September 19, 2024
Runtime version: 21.0.3+13-b509.15 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Operating system: Windows 10.0
Last action id: null

## Stack Trace
```
com.intellij.ide.script.IdeScriptException: org.graalvm.polyglot.PolyglotException: SyntaxError: Unexpected end of input
	at com.intellij.ide.script.IdeScriptEngineManagerImpl$EngineImpl.lambda$eval$1(IdeScriptEngineManagerImpl.java:259)
	at com.intellij.openapi.util.ClassLoaderUtil.computeWithClassLoader(ClassLoaderUtil.java:31)
	at com.intellij.ide.script.IdeScriptEngineManagerImpl$EngineImpl.eval(IdeScriptEngineManagerImpl.java:254)
	at yinzhengfei.ai.coding.iillILLlLI.iLIlLiIiiI(ToolkitUtil.java:148)
	at yinzhengfei.ai.coding.liIiLllIil.iLIlLiIiiI(CustomProviderSearchGroup.java:111)
	at yinzhengfei.ai.coding.IlIlLliiii$1.iLIlLiIiiI(ProviderRepository.java:202)
	at yinzhengfei.ai.coding.IlIlLliiii$iLIlLiIiiI.iLIlLiIiiI(ProviderRepository.java:307)
	at yinzhengfei.ai.coding.IlIlLliiii$iLIlLiIiiI.call(ProviderRepository.java:301)
	at com.intellij.concurrency.client.ClientIdPropagation.captureClientIdInCallable$lambda$5(ClientIdPropagation.kt:53)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$2.call(AnyThreadWriteThreadingSupport.kt:162)
	at com.intellij.concurrency.client.ClientIdPropagation.captureClientIdInCallable$lambda$5(ClientIdPropagation.kt:53)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.concurrency.client.ClientIdPropagation.captureClientIdInRunnable$lambda$3(ClientIdPropagation.kt:43)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.graalvm.polyglot.PolyglotException: SyntaxError: Unexpected end of input
	at <js>.:program(<eval>:19)
	at org.graalvm.polyglot.Context.eval(Context.java:403)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:485)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:453)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
	at com.intellij.ide.script.IdeScriptEngineManagerImpl$EngineImpl.lambda$eval$1(IdeScriptEngineManagerImpl.java:256)
	... 21 more
```

**Comment by yzhengfei** [comment]
Hi, this issue might be caused by problems with the JS script or exceptions during the parsing of data returned by the interface. The plugin provides an OpenAI interface request template that you can refer to for specifics.

![image](https://github.com/user-attachments/assets/3fe49021-63e4-4724-8b95-15623206943d)
![image](https://github.com/user-attachments/assets/ddec5b63-2433-4e35-9a85-322e6149e5ed)
